config/routes.rb
Rails.application.routes.draw do
  get '/game', to: 'play#game'

  get '/score', to: 'play#score'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/play_controller.rb
require 'open-uri'
require 'json'

class PlayController < ApplicationController
  def game
  	# @start_time = Time.now
  	# @player = params[:my_game]
  	@grid = generate_grid(10).join(" ")

  end

  # define all the variables through the following steps
  # get the attempt from the params
  # pas the start_time and the grid through hidden fields also in the params
  # then grab start_time and grid from the params as well
  # make sure everything is in the right format (Time class, array)

  def score
  	@end_time = Time.now
  	@attempt = params[:my_game]
  	@start_time = params[:start_time]
  	@grid1 = params[:grid]
  	# raise
  	@result = run_game(@attempt, @grid1, @start_time.to_i, @end_time.to_i)
  end

private 

def generate_grid(grid_size)
  Array.new(grid_size) { ('A'..'Z').to_a.sample }
end

def included?(guess, grid)
  guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
end

def compute_score(attempt, time_taken)
  time_taken > 60.0 ? 0 : attempt.size * (1.0 - time_taken / 60.0)
end

def run_game(attempt, grid, start_time, end_time)
  result = { time: end_time - start_time }

  score_and_message = score_and_message(attempt, grid, result[:time])
  result[:score] = score_and_message.first
  result[:message] = score_and_message.last

  result
end

def score_and_message(attempt, grid, time)
  if included?(attempt.upcase, grid)
    if english_word?(attempt)
      score = compute_score(attempt, time)
      [score, "well done"]
    else
      [0, "not an english word"]
    end
  else
    [0, "not in the grid"]
  end
end

def english_word?(word)
  response = open("https://wagon-dictionary.herokuapp.com/#{word}")
  json = JSON.parse(response.read)
  return json['found']
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/play/game.html.erb
<h1>Play#game</h1>
<p>Find me in app/views/play/game.html.erb</p>


<form action="/score" method="get">
  <input type="hidden" name="start_time" value="<%= Time.now %>">

  <input type="hidden" name="grid" value="<%= @grid %>">
<!--   <input type="hidden" name="attempt[id]" value="abcd">
 -->  Your word
  <input type="text" id="player" name= "my_game" placeholder="Write a word">
  <input type="submit">
</form>

<h1><%= @grid %></h1>

app/views/play/score.html.erb
<h1>Play#score</h1>
<p>Find me in app/views/play/score.html.erb</p>

<h1><%=@my_game %></h1>
<h1><%=@result %></h1>

<%= link_to "make a word", game_path %>